// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type EditCalendar struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

type EditEvent struct {
	ID          string       `json:"id"`
	Title       *string      `json:"title"`
	Location    *SetLocation `json:"location"`
	Description *string      `json:"description"`
	Start       *time.Time   `json:"start"`
	End         *time.Time   `json:"end"`
	Calendar    *string      `json:"calendar"`
}

type Location struct {
	Lat     *float64 `json:"lat"`
	Lon     *float64 `json:"lon"`
	Name    *string  `json:"name"`
	Address *string  `json:"address"`
}

type NewCalendar struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type NewEvent struct {
	Title       string       `json:"title"`
	Location    *SetLocation `json:"location"`
	Description string       `json:"description"`
	Start       time.Time    `json:"start"`
	End         time.Time    `json:"end"`
	Calendar    string       `json:"calendar"`
}

type SetLocation struct {
	Lat     *float64 `json:"lat"`
	Lon     *float64 `json:"lon"`
	Name    *string  `json:"name"`
	Address *string  `json:"address"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
