// Code generated by ObjectBox; DO NOT EDIT.

package db_model

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(EventBinding)
	model.RegisterBinding(CalendarBinding)
	model.LastEntityId(2, 3479788557646175786)
	model.LastIndexId(3, 2695485223480358088)

	return model
}
